FROM python:3

COPY clouds.yaml /etc/openstack/clouds.yaml
COPY requirements.txt /root/requirements.txt
RUN pip install setuptools --upgrade
RUN pip install -r /root/requirements.txt

ENV ANSIBLE_HOST_KEY_CHECKING False
CMD ["/usr/bin/tail","-f","-n0","/etc/hosts"]

